### ISSUE TITLE
SwiftDrop message is only being displayed for minimal amount of time

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/ParkenDD#105]
> funktionsmäßig klappt die Städte-Auswahl bei mir nicht wirklich gut, wenn ich die Stadt zum 1. Mal lade. Ich wähle die Stadt, gehe auf "Fertig", warte 1sec, dann kommt irgendein schwarzer Balken oben rein, der einen Text zeigt und geht nach gefühlt 10ms wieder weg. Dann muss ich nochmal auf "Fertig" drücken und komme dann erst zurück. Klappte aber irgendwie nur zu Beginn nicht so richtig - mittlerweile klappt es. Weiß nicht ob du Prefetchst und daher nur die ersten paar Sek nach dem App-Start die Städte noch nicht geladen sind, aber den Use Case dass ein Benutzer sofort nach dem Start die Stadt wechselt, kannst du ja nochmal testen. 

Just gonna quote @sibbl here :P

**Comment by kiliankoe** [comment]
Now reported by multiple testers, gonna have to check this out.

**Comment by sibbl** [comment]
Now I'm sad that my bug report alone wasn't worth further investigation :disappointed: :laughing:

**Comment by kiliankoe** [comment]
I just wasn't sure what was going on :D

**Comment by kiliankoe** [comment]
There's been a new release of SwiftDrop since and I haven't seen this bug. I did turn of the notification for outdated data temporarily in the current beta because of another bug, but if you tap on the setting for showing lots without any data in the app settings it should be displayed. Can you check if that still causes issues with the current beta on your end, @sibbl?

**Comment by sibbl** [comment]
Seems to work now :)

**Comment by kiliankoe** [comment]
Awesome, thanks! :) 

Let's close this issue and hope this bug doesn't resurface :D
