### ISSUE TITLE
Add "Export to Maps"

### ISSUE THREAD

**Issue by Feliix42** [kiliankoe/ParkenDD#112]
To improve the functionality of the app it would be nice if you could simply pick a parking lot from the app and jump over to maps, with the selected parking lot as destination, starting from your location (export to Maps).

Could be realized by swiping an entry to the left (or right) or something like that.

**Comment by kiliankoe** [comment]
This is already planned for Maps (and others, using a nifty little framework) in #95. But thanks for the suggestion!

I like the idea of the swipe gesture, but I'm hoping to (re)implement detail views (#71) soon, so that's probably where I'll be moving this option.
