### ISSUE TITLE
Better Optimal Sorting algorithm

### ISSUE THREAD

**Issue by balzer82** [kiliankoe/ParkenDD#114]
Formula should be: `sqrt(Entfernung^2 + (1/((2*(1-Belegung))^2 + 1))*Belegung^2)` und dabei `Entfernung` in Meter und `Belegung` normiert 0...1

`1/((2*(1-Belegung)` looks like this:
![formel_jk](https://cloud.githubusercontent.com/assets/3329893/10428258/6645813a-70f0-11e5-91c1-8225bcaae58c.png)

reason is, that crowded parking lots are rated down.

**Comment by kiliankoe** [comment]
Didn't get to it yet, sry. So I shouldn't merge your open pull request and incorporate this instead?

**Comment by balzer82** [comment]
No hurry, just a reminder. I can do this with the next pull request.

Which units do we have for Entfernung and Belegung?

__________________________________________
Mailbox.org - Damit privates privat bleibt

**Comment by kiliankoe** [comment]
Units are km and 0...1 (I think :D)

**Comment by kiliankoe** [comment]
closed in 5a12535c77e98826067fca522d3d2c1f79e6cc35
