### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by Lalithsai853** [kiliankoe/ParkenDD#168]
Is there any way to translate the app into English?

**Comment by Lalithsai853** [comment]
How can we implement the English translation into the Xcode project

**Comment by kiliankoe** [comment]
The app is already localized to English (besides German, Czech and Polish). You can find the translation [here](https://github.com/kiliankoe/ParkenDD/blob/master/ParkenDD/Supporting%20Files/Base.lproj/Localizable.strings). 

iOS automatically picks the language it displays based on your system language, but you can override this by going to the ParkenDD settings in the settings app.
