### ISSUE TITLE
Vorhersage der Belegung

### ISSUE THREAD

**Issue by balzer82** [kiliankoe/ParkenDD#47]
Ich habe beispielhaft für die Centrum-Galerie für das Jahr 2015 eine [Vorhersage der Belegung](http://mechlab-engineering.de/2015/03/vorhersage-der-parkhausbelegung-mit-offenen-daten/) (in %) mit Machine Learning entwickelt. Das könnte man als Experimental-Feature in die App einbauen.

Ich stelle mir so eine Art Slider vor, wenn man auf die Centrum-Galerie geht, wo man
|======+30min=======in 1h=========in 2h=========in 3h==..
und auch 
`am 18.08.2015 um 15Uhr`
über ein Date-Picker Tool in Android eingeben kann und dann die Belegung von der App zurück bekommt. Dazu müsste im einfachsten Fall [eine .CSV](http://mechlab-engineering.de/downloads/Centrum-Galerie-Belegung-Vorhersage-2015.csv) geparsed werden und der korrekte Wert daraus entnommen und angezeigt.

**Comment by kiliankoe** [comment]
Hatte deinen Blogpost dazu schon gelesen. Klingt super und wird auf jeden Fall einen Weg in die App finden! :+1:

**Comment by balzer82** [comment]
Idee ist, es erst mal Prototyp mäßig so hin zu biegen, damit man es vorzeigen kann, wie es laufen könnte mit OpenData und paar jungen Entwicklern die Bock haben und das wir einen schönen Showcase haben für Presse&Co.
Dann mal sehen ob sich Interessenten finden und man die anderen Parkhäuser oder sogar alle via API bereitstellen könnte.

**Comment by kiliankoe** [comment]
Klingt nur sinnvoll so. Für das nächste Release hier hab ich erstmal nen Stapel Fixes, UI Aufhübschungen und so drin. Werde das hier aber auf jeden Fall mal angehen und irgendwie einbauen, damit man was sehen kann.

**Comment by kiliankoe** [comment]
Dank Motivation von Johannes... :D

Schaut jetzt so hier aus aktuell (ist noch nicht auf Deutsch lokalisiert):
![csv](https://cloud.githubusercontent.com/assets/2625584/6908725/aaa1a3fe-d73f-11e4-8964-44e9b18b7562.gif)

**Comment by kiliankoe** [comment]
Hey Paul, wäre es möglich die Daten nochmal in halbstündlicher Auflösung zu bekommen? Viertelstündlich geht zwar recht gut, aber wie Johannes schon meinte ist die Auflösung vielleicht doch übertrieben. Leider können iOS Datepicker aber nicht auf stündliche Auflösung limitiert werden und ich würde ungern einfach auf die Stunde interpolieren, weil die Minutenauswahl dann einfach sinnlos rumliegt. Da kann man ihr schon ein paar Daten mit zur Hand geben ;) 

Thx :)

**Comment by kiliankoe** [comment]
Hab mal noch einen Graphen mit reingeschmissen. Würde den gerne nutzen um jeweils die Vorhersagedaten für die aktuell ausgewählte Woche (sprich die Woche um den ausgewählten Tag drumherum) anzuzeigen. Die dargestellten Daten sind aktuell jedoch noch recht fest die aus der Woche vom 4.7. - 10.7. Würde ich für das experimentelle Feature dann auch erstmal dabei belassen.

(Nochmal als GIF weil coole Animation)
![csv](https://cloud.githubusercontent.com/assets/2625584/7030165/f0205dca-dd62-11e4-9271-d4707c345722.gif)


Wenn ich dann noch die halbstündigen Daten reinschmeißen könnte würde ich das direkt für'n Release fertig machen wollen :)

**Comment by balzer82** [comment]
Sehr geil!

Daten in 30min Auflösung: http://mechlab-engineering.de/downloads/Centrum-Galerie-Belegung-Vorhersage-2015-30min.csv  


--
mailbox.org - Damit Privates privat bleibt



Am Dienstag, 7. April 2015 um 20:17 schrieb Kilian Koeltzsch:

**Comment by kiliankoe** [comment]
Danke dir! Ist submitted. Sind dann wohl wieder so ca. 8 Tage Wartezeit... Bin gespannt^^

**Comment by kiliankoe** [comment]
Mit c24a749 schließe ich das Issue hier mal jetzt. Forecast ist eingebaut, man sieht es an den Lots bei welchen Daten existieren und die Ansicht dafür ist funktional inkl. hübschem Graphen. So lang die Quelldaten auf dem Server liegen und von dort bereitgestellt werden ist alles super \o/
