### ISSUE TITLE
Helvetica > Avenir

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/ParkenDD#54]
Zumindest laut @sto3psl ... :D

**Comment by sto3psl** [comment]
Ich hab meine Gründe! 😄

**Comment by kiliankoe** [comment]
![avenir](https://cloud.githubusercontent.com/assets/2625584/7232008/697bd094-e779-11e4-8801-184664df377c.png)

Ich hab mir mal noch zwei Screenshots. Links die AirBnb App und rechts die Apple(!) Store App. Standardfonts, pff :P
