### ISSUE TITLE
Graph not clear

### ISSUE THREAD

**Issue by balzer82** [kiliankoe/ParkenDD#59]
In the newest version, the experimental feature 'Belegung' has a line graph, which is not clear. There is no x- or y-axis title, so is it the actual week from Mon-Sun or is it the week one has chosen by datepicker?

Would be nice, if there is also an indicator, showing 'now' in this graph for better understanding.

**Comment by kiliankoe** [comment]
Oooh, a line highlighting "now" and a second one for the selected date is a great idea!
