### ISSUE TITLE
Add year to datepicker

### ISSUE THREAD

**Issue by balzer82** [kiliankoe/ParkenDD#60]
Because of the year dependency, the date picker for the experimental feature (Vorhersage d. Belegung) should have a year, just to be clear.

**Comment by kiliankoe** [comment]
An iOS datepicker can be set to four different modes, `Time`, `Date`, `DateAndTime` and `CountDownTimer`. The only interesting one here (`DateAndTime`) displays the date as a day of a month (e.g. "Fri 1 May"), but also contains the year. There's no way to actually display this year in the picker itself besides throwing a label in the UI somewhere that displays the date that is currently selected, but that would duplicate the displayed information somewhat...

If a user wants to select a date in the coming year for example, he/she's just going to have to scroll down a bit^^ That's just how iOS does it. Throwing a second datepicker in there or building something completely custom either violates the iOS Human Interface Guidelines or is crappy UI. 

In the current version of the app (1.2) it's actually not possible to choose dates outside of 01.05.15-31.12.15 as I limited the datepicker to the range of data available in the CSV. It'll actually throw you back into that range if you try to pick something outside of it. This is of course going to be removed once there's an API to get this data from.
