### ISSUE TITLE
Info: Anzeigetafeln in der Stadt nicht konsistent

### ISSUE THREAD

**Issue by balzer82** [kiliankoe/ParkenDD#64]
Habe dieser Tage mal einen Reality-Check in der Stadt gemacht: Die freien Parkplätze, die z.B. an der Anzeigetafel auf dem [Dr.-Külz-Ring](https://www.google.de/maps/@51.047212,13.735741,3a,75y,277.61h,88.45t/data=!3m4!1e1!3m2!1sAwifiZ8Iu_VNyAkl0EeOzg!2e0) (auf Google StreetView ist da noch keine) angezeigt werden, stimmen nicht überein mit denen, die in der App gerade angezeigt wurden. Waren so +/- 20 Parkplätze Unterschied.

Das ist aber kein Fehler unsererseits, sondern die Tafeln in der Stadt werden nicht konsistent von der gleichen Datenquelle gespeist. Wenn man z.B. um die Ecke herum fährt und zur Centrum-Galerie abbiegt in die [Reitbahnstr.](https://www.google.de/maps/@51.045908,13.733495,3a,75y,211.46h,88.05t/data=!3m4!1e1!3m2!1sk4AOckZBV7xteFkqjCZtaQ!2e0), dann steht dort wieder eine Tafel und diese Zahlen stimmten exakt mit den Zahlen in der App überein.

Falls also Beschwerden von jemandem kommen sollten: Da können wir nix für! :-)

**Comment by kiliankoe** [comment]
> Falls also Beschwerden von jemandem kommen sollten: Da können wir nix für! :-)

:+1: :+1: :grin:

**Comment by kiliankoe** [comment]
Ich schließ' das hier mal, wird sich ja eh nicht ändern und wir wissen Bescheid ;)
